# Generated by Django 2.0.7 on 2018-08-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180805_2320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'wallet')},
        ),
    ]
